{% set name = "pylru" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5a153ec9866a2c18676a42df8340f4645bfc84a4eff5ef3c68870d5e29ffe169

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - pylru

about:
  home: https://github.com/jlhutch/pylru
  license: GPL-2.0
  license_file: LICENSE.txt
  summary: A least recently used (LRU) cache implementation

extra:
  recipe-maintainers:
    - nehaljwani
